apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.port }}
    protocol: TCP
  selector:
    app: {{ .Values.postgres.name }}